### ISSUE TITLE
About QNX Network

### ISSUE THREAD

**Issue by Sphinxes0o0** [xtang2010/articles#1]
Hi, xtang,
         Appreciate for the article you shared.  Will there be an introduction about the network ?

**Comment by xtang2010** [comment]
Anything particular about the network? :-)

**Comment by Sphinxes0o0** [comment]
1. about qnx tcp/ip stack: io-pkt or io-sock
2. the virtual network on qnx

And not limited to these I think of, any other articles sharing is also very good !

Thangks!
